apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  creationTimestamp: "2022-12-02T17:35:14Z"
  generation: 1
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
  name: tanzu-java-web-app
  namespace: mae
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/Mpluya/tanzu-java-web-app-jenkins.git